---
title: "rivnet_to_river::class"
author: "Yifan Wang"
date: "2024-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(sf)
library(dplyr)
library(mapview)
library(riverdist)
library(webshot)
library(OCNet)
library(rivnet)
library(stringr)

shapefilePath <- "D:/Dissertation/REC2_Layers_Shapefiles/River_Lines.shp"

riverLines <- st_read(shapefilePath)


```

#查询特定ID的连接网络

```{r}
#ID=263375
ID=98018
findConnected <- function(targetID, riverLines, visited = numeric()) {
  # 初始化一个队列，存放当前层级待访问的节点
  queue <- c(targetID)
  while (length(queue) > 0) {
    # 取出队列的第一个元素
    currentID <- queue[1]
    queue <- queue[-1]
    # 检查是否遇到结束标志
    if(currentID == -1) {
      next # 跳过当前迭代
    }
    # 将当前节点添加到已访问列表
    if (!currentID %in% visited) {
      visited <- c(visited, currentID)
      # 找到所有下游节点，即当前节点作为NextDownID的节点
      downstreamIDs <- riverLines$HydroID[riverLines$NextDownID == currentID]
      
      # 找到所有上游节点，即当前节点的HydroID在其他节点的NextDownID中的节点
      upstreamIDs <- riverLines$NextDownID[riverLines$HydroID == currentID]
      
      # 将未访问的下游和上游节点添加到队列中
      for (id in c(downstreamIDs, upstreamIDs)) {
        if (!id %in% visited ) { # 确保不将结束标志或已访问的节点添加到队列
          queue <- c(queue, id)
        }
      }
    }
  }
  
  # 移除列表中的-1，如果存在
  visited <- visited[visited != -1]
  
  return(visited)
}

# 使用定义的函数，从HydroID=98753开始找到所有相连的河流段
connected_hydroIDs <- findConnected(ID, riverLines)

# 输出找到的HydroID数量
cat("Found connected HydroIDs count:", length(connected_hydroIDs), "\n")



# 如果你想获取这些HydroID对应的完整行数据，可以使用以下代码
connected_river_segments <- riverLines[riverLines$HydroID %in% connected_hydroIDs, ]
set.seed(123) # 为了可重复性
connected_river_segments$Value <- runif(nrow(connected_river_segments), min = 0, max = 100)
mapview(connected_river_segments%>%filter(StreamOrde!=1), zcol = 'Value', col.regions = colorRampPalette(c("blue", "yellow", "red"))(100))
mapview(connected_river_segments%>%filter(StreamOrde!=1))

```

#通过Nextdown_id=-1 确定outlet

```{r}



#通过Nextdown_id=-1 确定outlet
outlet_row<-connected_river_segments[which(connected_river_segments$NextDownID==-1),]

outlet_pos<-c(outlet_row$downcoordX,outlet_row$downcoordY)
x_max<-max(connected_river_segments$upcoordX, connected_river_segments$downcoordX)
y_max<-max(connected_river_segments$upcoordY, connected_river_segments$downcoordY)
x_min<-min(connected_river_segments$upcoordX, connected_river_segments$downcoordX)
y_min<-min(connected_river_segments$upcoordY, connected_river_segments$downcoordY)

# 从riverLines中筛选出在范围内的出口
selected_segments <- riverLines %>%
  filter(NextDownID == -1, # NextDownID等于-1
         upcoordX >= x_min & upcoordX <= x_max, # X坐标在范围内
         downcoordX >= x_min & downcoordX <= x_max, # X坐标在范围内
         upcoordY >= y_min & upcoordY <= y_max, # Y坐标在范围内
         downcoordY >= y_min & downcoordY <= y_max) # Y坐标在范围内
# 查看筛选后的数据
print(selected_segments)
outlet_rows <- selected_segments[which(selected_segments$NextDownID == -1),]
# 将出口的upcoordX和upcoordY坐标存储到data.frame中
outlet_pos_df <- data.frame(x=outlet_rows$upcoordX, y=outlet_rows$upcoordY)
# 打印outlet_pos_df查看结果
print(outlet_pos_df)


TAUDEM_PATH='C:/Program Files/TauDEM'
r2 <- extract_river(outlet=c(outlet_row$downcoordX,outlet_row$downcoordY),
	EPSG=2193, #New Zealand NZTM2000
	ext=c(x_min,x_max,y_min,y_max),
	z=10)
plot(r2)

#colour represent the elevation
draw_elev3D_OCN(r2,drawRiver = TRUE)
```

```{r}
source("D:/Dissertation/ALL_code_file/get_trout_pop_functions.R")


#slope0 is the slope of the outlet pixel
#OCNwe <- landscape_OCN(r2, slope0 = tail(r2$FD$slope,1))
thr <- find_area_threshold_OCN(r2)
#calculation the elevation of the lowest pixel(according to the landscape_OCN)


# find index corresponding to thr$Nnodes ~= 
indThr <- which(abs(thr$nNodesAG - 70) == min(abs(thr$nNodesAG - 70)))
indThr <- max(indThr) # pick the last ind_thr that satisfies the condition above
thrA20 <- thr$thrValues[indThr] # corresponding threshold area
OCNwe <- aggregate_OCN(r2, thrA = thrA20)
par(mai=c(0.1,0,0.1,0))
draw_subcatchments_OCN(OCNwe)
points(OCNwe$AG$X,OCNwe$AG$Y, pch = 21, col = "blue", bg = "blue")



OCNwe <- rivergeometry_OCN(OCNwe, widthMax = 5)   # evaluate river width 
K <- 10*OCNwe$RN$width                             # calculate carrying capacity 
#pop0 <- sample_from_density(density_data, n = OCNwe$RN$nNodes)*OCNwe$RN$leng/1000  # initial random population vector
pop0<-weighted_pop0
nTimestep <- 10                                   # number of timesteps
r <- 1+average_annual_growth_rate                    # proliferation rate
pd <- 0.8                                         # probability to move downstream
pu <- 1 - pd                                       # probability to move upstream
Go <- 0.2482                                            # parameter controlling mobility 
# (no. individuals exiting from outlet node at carrying capacity is pu*Go) 
## Weights for upstream movement
Y <- rep(1,OCNwe$RN$nNodes)                    
for (i in 1:OCNwe$RN$nNodes){
  if (i != OCNwe$RN$outlet){
    Y[i] <- OCNwe$RN$A[i]/(OCNwe$RN$W[ , OCNwe$RN$downNode[i]] %*% OCNwe$RN$A)
  }
}
GKK <- rep(0, OCNwe$RN$nNodes)
for (i in (1:OCNwe$RN$nNodes)){
  path <- OCNwe$RN$downstreamPath[[i]][[OCNwe$RN$outlet]] # select path
  prod <- Go                                                # initialize product of Y 
  for (j in path){
    prod <- prod*Y[j]
  }
  GKK[i] <- (pu/pd)^(length(path))*prod  
}
## Run metapopulation model
pop <- matrix(data=0,ncol=nTimestep,nrow=OCNwe$RN$nNodes)  # metapopulation matrix
pop[,1] <- pop0                                              # initialization
for (t in 2:nTimestep){
  print(t)
  for (i in 1:OCNwe$RN$nNodes){
    pop[i, t] <- 
      # Beverton-Holt growth model
      r*pop[i, t-1]/(1 + pop[i, t-1]*(r-1)/K[i]) +
      # individuals exiting from node i
                - (pu*(sum(OCNwe$RN$W[ , i])>0) + pd*(sum(OCNwe$RN$W[i, ])>0)) * 
      GKK[i] * (pop[i,t-1]/K[i]) +
      # individuals entering in i from the upstream nodes
                + pd * OCNwe$RN$W[ , i] %*% (GKK*pop[ , t-1]/K) +
      # individuals entering in i from the downstream node
                + pu * Y[i] * OCNwe$RN$W[i, ] %*% (GKK*pop[ , t-1]/K) 
    
  }
}
par(mfrow = c(1, 2))
plot(pop[OCNwe$RN$outlet, ], type = "l", ylim = c(0, r*K[OCNwe$RN$outlet]), col = "red", 
     xlab = "Time", ylab = "Population/KM", lwd = 2)
title("Evolution of outlet local pop. size")
lines(c(1, nTimestep),c(K[OCNwe$RN$outlet], K[OCNwe$RN$outlet]), col = "red", lty = 2)

plot(colSums(pop), type = "l", xlab = "Time", ylab = "Population", lwd = 2, ylim = c(0, 1.05*sum(K)))
lines(c(1, nTimestep), c(sum(K),sum(K)), lty = 2)
title("Evolution of metapop. size")
par(mfrow = c(2, 2), mai = c(0.1, 0, 0.2, 0))
draw_thematic_OCN(pop[,1], OCNwe, colLevels = c(0.5*max(pop), max(pop), 100),
                  drawNodes = FALSE)
title("Time = 1")
draw_thematic_OCN(pop[,3], OCNwe, colLevels = c(0.5*max(pop), max(pop), 100),
                  drawNodes = FALSE)
title("Time = 3")
draw_thematic_OCN(pop[,7], OCNwe, colLevels = c(0.4*max(pop), max(pop), 100),
                  drawNodes = FALSE)
title("Time = 7")
draw_thematic_OCN(pop[,10], OCNwe, colLevels = c(0.5*max(pop), max(pop), 100),
                  drawNodes = FALSE)
title("Time = 10")
```

#找到河流关键节点
```{r}
#根据一个上游节点连接的下游节点数量以及这些下游河段的长度来赋予这个上游节点一个权重
# 初始化每个节点的权重为0
node_weights <- numeric(length(OCNwe$RN$downNode))

# 遍历每个节点计算权重
for (i in seq_along(OCNwe$RN$downNode)) {
  # 找到当前节点直接下游的所有节点
  downstream_nodes <- which(OCNwe$RN$downNode == i)
  # 计算下游节点的数量
  num_downstream <- length(downstream_nodes)
  # 如果有下游节点，累加这些下游节点的河段长度
  if (num_downstream > 0) {
    total_length_downstream <- sum(OCNwe$RN$leng[downstream_nodes])
    # 以下游节点数量和下游河段长度总和的乘积为例计算权重
    node_weights[i] <- num_downstream * total_length_downstream/1000
  }
}
# Assuming draw_thematic_OCN can be adapted or is suitable for this purpose
draw_thematic_OCN(node_weights, OCNwe, colLevels = c(0, max(node_weights), 100),
                  drawNodes = FALSE)  # Ensure drawNodes is set appropriately
title("Node Weights Representation")




```
```{r}
#Influence[d(i)]=Influence[d(i)]+Influence[i]×(upstreamInfluenceWeight)^l
#这里Influence}[i]表示节点i当前的影响力值，upstreamInfluenceWeight是上游节点对下游节点的影响力权重，l是从节点i到达下游节点的层级数，d(i)是节点i的直接下游节点。
traceback_matrix <- get_traceback(connectivity = 4, OCNwe = OCNwe)
steps_matrix <- calculate_steps_to_downstream(traceback_matrix, OCNwe)
influence_results <- calculateInfluenceDynamically(upstreamInfluenceWeight=0.5, OCNwe,traceback_matrix, steps_matrix)

influence_results <- calculateInfluenceDynamically(connectivity=100, upstreamInfluenceWeight=0.5, OCNwe)
normalized_influences <- (influence_results - min(influence_results)) / (max(influence_results) - min(influence_results))
```

```{r}
#upstreamInfluenceWeight值从0到1，步长为0.1的变化结果
library(ggplot2)
# 初始化一个空的数据框来存储结果
results_df <- data.frame(Influence = numeric(), Weight = factor())
# 遍历upstreamInfluenceWeight值从0到1，步长为0.1
for (weight in seq(0.1, 1, by=0.1)) {
  influence_results <- calculateInfluenceDynamically(connectivity=10, upstreamInfluenceWeight=weight, OCNwe)
  normalized_influences <- (influence_results - min(influence_results)) / (max(influence_results) - min(influence_results))
  # 将当前权重下的影响力结果添加到数据框
  results_df <- rbind(results_df, data.frame(Influence = normalized_influences, Weight = as.factor(sprintf("%.1f", weight))))
}
ggplot(results_df, aes(x = Influence, fill = Weight)) +
  geom_density(alpha = 0.7) +
  scale_fill_brewer(palette = "Spectral") +
  labs(title = "Normalized Influence Distribution by Upstream Influence Weight",
       x = "Normalized Influence",
       y = "Density",
       fill = "Upstream Influence\nWeight") +
  coord_cartesian(ylim = c(0, 15)) +  # 可能需要根据你的数据调整这个范围
  theme_minimal()




```
```{r}
library(ggplot2)
library(plotly)
results_df <- data.frame(Influence = numeric(), Connectivity = factor())

# 遍历connectivity值从1到10
for (conn in seq(1,20,6)) {
  influence_results <- calculateInfluenceDynamically(connectivity=conn, upstreamInfluenceWeight=0.7, OCNwe)
  normalized_influences <- (influence_results - min(influence_results)) / (max(influence_results) - min(influence_results))
  
  # 将当前connectivity下的影响力结果添加到数据框
  results_df <- rbind(results_df, data.frame(Influence = normalized_influences, Connectivity = as.factor(conn)))
}

gg_plot <- ggplot(results_df, aes(x = Influence, fill = Connectivity)) +
  geom_density(alpha = 0.7) +
  scale_fill_brewer(palette = "Spectral") +
  labs(title = "Normalized Influence Distribution by Connectivity",
       x = "Normalized Influence",
       y = "Density",
       fill = "Connectivity") +
  theme_minimal()

# 将ggplot对象转换为plotly对象
plotly_plot <- ggplotly(gg_plot)

# 显示交互式图表
plotly_plot
```


#simulated pop from the weighted river
```{r}

# 根据密度函数抽样，得到预期的种群总数
sampled_trout_populations <- sample_from_density(density_data, n = length(OCNwe$RN$A))
# 求得所有抽样值的总和，表示整个河流系统的预期鱼类种群总数量
total_fish_population <- sum(sampled_trout_populations*OCNwe$RN$leng/1000) 

# 归一化影响力，确保所有节点的影响力加起来为1
normalized_influences <- influence_results  / sum(influence_results )

# 根据归一化的影响力来分配鱼类种群到每个节点
allocated_fish_populations <- total_fish_population * normalized_influences

# 打印出来或进行后续分析
weighted_pop0<-allocated_fish_populations*OCNwe$RN$leng/1000


```


